### ISSUE TITLE
Cannot build checked out share-button

### ISSUE THREAD

**Issue by vbledar** [carrot/share-button#271]
I am trying to build the project (gulp build) but I receive the following error:

/Projects/General/share-button/node_modules/gulp-accord/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		^
TypeError: node.serializeToString is not a function
    at XMLSerializer.serializeToString (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/node_modules/xmldom/dom.js:906:7)
    at SVGImage._addSprite (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_image.js:199:40)
    at SVGImage._parseNode (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_image.js:143:20)
    at SVGImage._parseNode (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_image.js:148:16)
    at SVGImage._parseSvg (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_image.js:99:18)
    at new SVGImage (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_image.js:31:12)
    at Object.module.exports.addToIndex (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_cache.js:65:15)
    at Object.module.exports.init (/Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/lib/svg_cache.js:25:14)
    at /Users/xxxx/Projects/General/share-button/node_modules/postcss-svg/dist/index.js:24:16
    at LazyResult.run (/Users/xxxx/Projects/General/share-button/node_modules/poststylus/node_modules/postcss/lib/lazy-result.js:206:20)

1) node --version
v4.2.3
2) npm --version
2.14.7

**Comment by rejas** [comment]
It's an issue with xmldom, see https://github.com/jindw/xmldom/issues/146

**Comment by hhsnopek** [comment]
it seems that the issue has been resolved - let me know if you're still having issues @vbledar 
> jindw commented on Jan 13
> sorry :(
> it 's my fault.
> fixed in 0.1.21
